### ISSUE TITLE
Add the 2021 May workshop info on the NCPI portal

### ISSUE THREAD

**Issue by linikujp** [anvilproject/anvil-portal#1119] opened 2021-06-08 15:13 UTC
The 2021 May workshop info needs to be put on the NCPI portal. 
I am working on a short summary for the meeting note. But for now, let's put the long meeting note version on, and I will ask to change the link once the short summary is done. 
Thanks,
Asiyah

**Comment by NoopDog** [comment] 2021-06-12 08:19
Dupe of #1108

**Closed by NoopDog** 2021-06-12 08:19 UTC
Labels: NCPI

**Comment by NoopDog** [comment] 2021-06-12 08:20
This is now implemented. 

See https://anvilproject.org/ncpi/progress-updates

Cheers,
D

**Comment by linikujp** [comment] 2021-06-14 16:16
Hi Dave,
Feedbacks from us to improve:
1. Instead of "agenda", can you add "links to slides and recordings included"?
2. Add a separate link to slides for each day.
These two seems redundant. We definitely want the No. 2. to be done. It's up to you to decide if you will also considering the No.1.
Thanks,
Asiyah

**Comment by NoopDog** [comment] 2021-06-14 16:48
HI @linikujp Yes, I did not realize we had the slides ready. We can add a link for the slides.

**Comment by NoopDog** [comment] 2021-06-14 16:51
@linikujp, I created #1134 to track the addition of the slides. Cheers, D
