### ISSUE TITLE
Sanitize links to Terra documentation to not include the titles

### ISSUE THREAD

**Issue by kozbo** [anvilproject/anvil-portal#729] opened 2020-12-09 16:35 UTC
From Allie on slack: For anyone who is linking to Terra documentation (on Zendesk): Links should only include the url up to the random number string. Don’t include the title!!
i.e. use 
https://support.terra.bio/hc/en-us/articles/360046295092 
not 
https://support.terra.bio/hc/en-us/articles/360046295092-Set-up-billing-with-300-Google-credits-to-explore-Terra

**Comment by NoopDog** [comment] 2020-12-09 16:42
Dupe of #728

**Closed by NoopDog** 2020-12-09 16:42 UTC
