### ISSUE TITLE
Include icon/link to AnVIL Project Youtube channel

### ISSUE THREAD

**Issue by MoHeydarian** [anvilproject/anvil-portal#574] opened 2020-08-12 16:40 UTC
Include icon/link to AnVIL Project Youtube channel along with Twitter, Slack, Github icons at the bottom of the pages.

AnVIL Project Youtube channel: https://www.youtube.com/channel/UCBbHCj7kUogAMFyBAzzzfUw

**Comment by MillenniumFalconMechanic** [comment] 2020-11-13 22:38
Dupe of #520.

**Closed by MillenniumFalconMechanic** 2020-11-13 22:38 UTC
