### ISSUE TITLE
[AnVIL Next] Create script to download CSER research material files

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [anvilproject/anvil-portal#2683] opened 2023-05-11 20:05 UTC
#### Need
CSER research materials will be statically hosted in the Next.js app and referenced and available for download from the corresponding research materials page.

#### Approach
Write a script to download the [existing research materials](https://cser-consortium.org/cser-research-materials) and add downloads to the Next.js app.

**Comment by NoopDog** [comment] 2023-06-07 22:21
Dupe of #2714 closing

**Closed by NoopDog** 2023-06-07 22:21 UTC
