### ISSUE TITLE
Update Data Submission Guide and Consortia Section

### ISSUE THREAD

**Issue by NoopDog** [anvilproject/anvil-portal#1079] opened 2021-05-14 17:05 UTC
#### Need
1. The content in the consortia section is a bit out of date and could use elaboration.
1. The current data submission guide is quite long making it difficult to see the overall picture and find relevant parts. 

#### Approach
1. Update the guide from https://docs.google.com/document/d/1OnBCtYdDYqwUgx0aApwCm4_vupO8uFrbCHesyNPxGPM/edit#heading=h.wuhw355xf5mk
1. Split out into different documents as it is quite long and splitting it out will aid discovery of the content.

#### Definition of Done
1. The guide is updated with text from the above document.
1. The Consortia section is renamed "Data Submitters".
1. The guide is split into:
    1. Submitting Data
    1. Data Requirements
    1. Data Approval Process
    1. Ingesting Data

**Comment by kozbo** [comment] 2021-05-27 21:22
related to or maybe a duplicate of 
#959

**Closed** 2021-05-29 17:13 UTC
