### ISSUE TITLE
[AnVIL Portal] Terms of Service

### ISSUE THREAD

**Issue by frano-m** [anvilproject/anvil-portal#2697] opened 2023-05-23 03:50 UTC
#### Approach
Start with a stub:
- [x] Path: anvil-explorer-tos
- [x] Title: AnVIL Explorer Terms of Service
- [ ] Content: TBD **Waiting for content to be finalized by UCSC legal.**

**Comment by MillenniumFalconMechanic** [comment] 2023-05-23 04:03
Waiting for content.

**Comment by MillenniumFalconMechanic** [comment] 2023-10-04 19:30
Duplicate of https://app.zenhub.com/workspaces/team-boardwalk-5d680d7e3eeb5f1bbdf5668f/issues/gh/databiosphere/data-browser/3684.

**Closed by MillenniumFalconMechanic** 2023-10-04 19:30 UTC
