### ISSUE TITLE
Add NCPI cloud costs page?

### ISSUE THREAD

**Issue by kozbo** [anvilproject/anvil-portal#793] opened 2021-02-09 18:27 UTC
Should we have a page that tracks the work going on in the members of the NCPI effort with regards to the cloud costs?

We should include a link to the STRIDES FAQ there.
https://cloud.cit.nih.gov/files/STRIDES-Initiative-Frequently-Asked-Questions.pdf

**Comment by MillenniumFalconMechanic** [comment] 2021-02-11 19:17
Dupe of #809.

**Closed** 2021-02-11 19:19 UTC
